---
name: FlashSpace

options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  groupSortPosition: top
  bundleIdPrefix: pl.wojciechkulik
  fileTypes:
    icon:
      file: true

targets:
  FlashSpace:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: [FlashSpace]
    resources:
      - path: FlashSpace/Resources
    info:
      path: FlashSpace/Info.plist
      properties: {}

    settings:
      base:
        MARKETING_VERSION: 4.17.78
        CURRENT_PROJECT_VERSION: 78
        ASSETCATALOG_COMPILER_APPICON_NAME: FlashSpaceIcon
        CODE_SIGN_ENTITLEMENTS: FlashSpace/FlashSpace.entitlements
        DEVELOPMENT_TEAM: "${XCODE_DEVELOPMENT_TEAM}"
        ENABLE_HARDENED_RUNTIME: true
        DEAD_CODE_STRIPPING: true
        ENABLE_USER_SCRIPT_SANDBOXING: false
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: FlashSpace
        INFOPLIST_KEY_NSHumanReadableCopyright: © 2025 Wojciech Kulik. All rights reserved.
      configs:
        debug:
          INFOPLIST_KEY_CFBundleDisplayName: FlashSpace Dev
          PRODUCT_NAME: FlashSpace-Dev
          PRODUCT_BUNDLE_IDENTIFIER: pl.wojciechkulik.FlashSpace.dev

    dependencies:
      - sdk: ServiceManagement.framework
